data<-read.csv("household_power_consumption.txt", sep=";")
days<-subset(data, Date=="1/2/2007" | Date=="2/2/2007")
SM1<-as.numeric(as.character(days$Sub_metering_1))
SM2<-as.numeric(as.character(days$Sub_metering_2))
SM3<-as.numeric(as.character(days$Sub_metering_3))
plot(SM1, pch=NA_integer_, ylab="Energy Sub Metering", xaxt="n")
lines(SM1, col="black")
lines(SM2, col="red")
lines(SM3, col="blue")
labeldays=c("Thu", "Fri", "Sat")
axis(1, at=c(1,1440,2880), labeldays)
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
#save file
dev.copy(png,"Plot3.png")
dev.off()